### ISSUE TITLE
Set up a GitHub action

### ISSUE THREAD

**Issue by Ambivalentalfa** [Workflomics/workflomics-QCmetric#13]
One of the next steps should be setting up a GitHub action that runs the tests to make sure the code runs on a new machine and that the tests pass. 

This also requires all methods to have test arguments, so you can try them on smaller sets.

**Comment by vedran-kasalica** [comment]
@Ambivalentalfa was this one resolved in #16?

**Comment by Ambivalentalfa** [comment]
@vedran-kasalica it was!
