### ISSUE TITLE
Renaming to something other than "QCmetric"?

### ISSUE THREAD

**Issue by magnuspalmblad** [Workflomics/workflomics-QCmetric#17]
The term "QC metric" gives associations to data/process quality control metrics (see e.g. https://doi.org/10.1002/mas.21544, https://doi.org/10.1021/acsmeasuresciau.3c00070, https://www.biorxiv.org/content/10.1101/2024.04.12.589318v2.full or https://doi.org/10.26434/chemrxiv-2024-0m8dm), which are closer to the functional, run-time, workflow benchmarks. It is also a bit broad, if this is only about the literature-based metric.

**How about a more descriptive and specific name, such as "pubmetric"?**

We can also refer to the individual metrics by the mathematical function or graph theoretical measure used to calculate them, or the "Nilsson score" for something composite or customized.

**Comment by vedran-kasalica** [comment]
I like `pubmetric`!

**Comment by Ambivalentalfa** [comment]
pubmetric it is!
